package v1alpha1
/*
Copyright 2026.















































































































}	SchemeBuilder.Register(&GpuOperator{}, &GpuOperatorList{})func init() {}	Items           []GpuOperator `json:"items"`	metav1.ListMeta `json:"metadata,omitempty"`	metav1.TypeMeta `json:",inline"`type GpuOperatorList struct {// GpuOperatorList contains a list of GpuOperator// +kubebuilder:object:root=true}	Status GpuOperatorStatus `json:"status,omitempty"`	Spec   GpuOperatorSpec   `json:"spec,omitempty"`	metav1.ObjectMeta `json:"metadata,omitempty"`	metav1.TypeMeta   `json:",inline"`type GpuOperator struct {// GpuOperator is the Schema for the gpuoperators API// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"// +kubebuilder:printcolumn:name="Driver Version",type=string,JSONPath=`.spec.driverVersion`// +kubebuilder:printcolumn:name="State",type=string,JSONPath=`.status.state`// +kubebuilder:resource:scope=Namespaced// +kubebuilder:subresource:status// +kubebuilder:object:root=true}	ObservedGeneration int64 `json:"observedGeneration,omitempty"`	// +optional	// ObservedGeneration is the generation of the GpuOperator CR that was last processed	InstalledVersion string `json:"installedVersion,omitempty"`	// +optional	// InstalledVersion is the version of the GPU operator currently installed	Conditions []metav1.Condition `json:"conditions,omitempty"`	// +optional	// If all Conditions are met, State is expected to be in StateReady.	// Conditions contain a set of conditionals to determine the State of Status.	Status `json:",inline"`type GpuOperatorStatus struct {// GpuOperatorStatus defines the observed state of GpuOperator}	Memory string `json:"memory,omitempty"`	// +optional	// Memory resource requirement	CPU string `json:"cpu,omitempty"`	// +optional	// CPU resource requirementtype Resources struct {// Resources defines CPU and memory}	Requests *Resources `json:"requests,omitempty"`	// +optional	// Requests defines the minimum resources for the operator	Limits *Resources `json:"limits,omitempty"`	// +optional	// Limits defines the maximum resources for the operatortype ResourceRequirements struct {// ResourceRequirements defines CPU and memory requirements}	Resources *ResourceRequirements `json:"resources,omitempty"`	// +optional	// Resources defines resource limits for GPU operator components	ValuesConfigMapName string `json:"valuesConfigMapName,omitempty"`	// +optional	// If specified, these values will be used instead of the default values	// ValuesConfigMapName is the name of the ConfigMap containing custom Helm values	Namespace string `json:"namespace,omitempty"`	// +optional	// +kubebuilder:default="gpu-operator"	// Namespace where the GPU operator will be installed	DriverVersion string `json:"driverVersion,omitempty"`	// +optional	// +kubebuilder:default="570"	// Compatible with Garden Linux kernel versions in Kyma clusters	// DriverVersion specifies the NVIDIA driver version to installtype GpuOperatorSpec struct {// GpuOperatorSpec defines the desired state of GpuOperator)	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"import (package v1alpha1*/limitations under the License.See the License for the specific language governing permissions andWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.distributed under the License is distributed on an "AS IS" BASIS,Unless required by applicable law or agreed to in writing, software    http://www.apache.org/licenses/LICENSE-2.0You may obtain a copy of the License atyou may not use this file except in compliance with the License.Licensed under the Apache License, Version 2.0 (the "License");