package cmd
/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software







































































































































}	}		os.Exit(1)		setupLog.Error(err, "problem running manager")	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {	setupLog.Info("starting manager")	}		os.Exit(1)		setupLog.Error(err, "unable to set up ready check")	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {	}		os.Exit(1)		setupLog.Error(err, "unable to set up health check")	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {	// +kubebuilder:scaffold:builder	}		os.Exit(1)		setupLog.Error(err, "unable to create controller", "controller", "GpuOperator")	}).SetupWithManager(mgr); err != nil {		Scheme: mgr.GetScheme(),		Client: mgr.GetClient(),	if err = (&controller.GpuOperatorReconciler{	}		os.Exit(1)		setupLog.Error(err, "unable to start manager")	if err != nil {	})		LeaderElectionID:       "gpu-operator.kyma-project.io",		LeaderElection:         enableLeaderElection,		HealthProbeBindAddress: probeAddr,		WebhookServer:          webhookServer,		Metrics:                metricsServerOptions,		Scheme:                 scheme,	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{	}		TLSOpts:       tlsOpts,		SecureServing: secureMetrics,		BindAddress:   metricsAddr,	metricsServerOptions := metricsserver.Options{	// - https://book.kubebuilder.io/reference/metrics.html	// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/server	// More info:	// Metrics endpoint is enabled in 'config/default/kustomization.yaml'. The Metrics options configure the server.	})		TLSOpts: tlsOpts,	webhookServer := webhook.NewServer(webhook.Options{	}		tlsOpts = append(tlsOpts, disableHTTP2)	if !enableHTTP2 {	}		c.NextProtos = []string{"http/1.1"}		setupLog.Info("disabling http/2")	disableHTTP2 := func(c *tls.Config) {	// - https://github.com/advisories/GHSA-4374-p667-p6c8	// - https://github.com/advisories/GHSA-qppj-fm5r-hxr3	// Rapid Reset CVEs. For more information see:	// prevent from being vulnerable to the HTTP/2 Stream Cancellation and	// due to its vulnerabilities. More specifically, disabling http/2 will	// if the enable-http2 flag is false (the default), http/2 should be disabled	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))	flag.Parse()	opts.BindFlags(flag.CommandLine)	}		Development: true,	opts := zap.Options{		"If set, HTTP/2 will be enabled for the metrics and webhook servers")	flag.BoolVar(&enableHTTP2, "enable-http2", false,		"If set, the metrics endpoint is served securely via HTTPS. Use --metrics-secure=false to use HTTP instead.")	flag.BoolVar(&secureMetrics, "metrics-secure", true,			"Enabling this will ensure there is only one active controller manager.")		"Enable leader election for controller manager. "+	flag.BoolVar(&enableLeaderElection, "leader-elect", false,	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")		"Use :8443 for HTTPS or :8080 for HTTP, or leave as 0 to disable the metrics service.")	flag.StringVar(&metricsAddr, "metrics-bind-address", "0", "The address the metrics endpoint binds to. "+	var tlsOpts []func(*tls.Config)	var enableHTTP2 bool	var secureMetrics bool	var probeAddr string	var enableLeaderElection bool	var metricsAddr stringfunc main() {}	// +kubebuilder:scaffold:scheme	utilruntime.Must(operatorv1alpha1.AddToScheme(scheme))	utilruntime.Must(clientgoscheme.AddToScheme(scheme))func init() {)	setupLog = ctrl.Log.WithName("setup")	scheme   = runtime.NewScheme()var ()	// +kubebuilder:scaffold:imports	"github.com/kyma-project/gpu-operator/internal/controller"	operatorv1alpha1 "github.com/kyma-project/gpu-operator/api/v1alpha1"	"sigs.k8s.io/controller-runtime/pkg/webhook"	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"	"sigs.k8s.io/controller-runtime/pkg/log/zap"	"sigs.k8s.io/controller-runtime/pkg/healthz"	ctrl "sigs.k8s.io/controller-runtime"	clientgoscheme "k8s.io/client-go/kubernetes/scheme"	utilruntime "k8s.io/apimachinery/pkg/util/runtime"	"k8s.io/apimachinery/pkg/runtime"	_ "k8s.io/client-go/plugin/pkg/client/auth"	// to ensure that exec-entrypoint and run can make use of them.	// Import all Kubernetes client auth plugins (e.g. Azure, GCP, OIDC, etc.)	"os"	"flag"	"crypto/tls"import (package main*/limitations under the License.See the License for the specific language governing permissions andWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.distributed under the License is distributed on an "AS IS" BASIS,